# Generated by Django 3.0.5 on 2022-11-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentresearch',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currentresearch',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
