# Generated by Django 3.0.5 on 2022-11-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221115_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('fb', models.URLField()),
                ('linkedin', models.URLField()),
                ('img', models.ImageField(null=True, upload_to='UserPhoto/%y')),
            ],
        ),
    ]
