# Generated by Django 3.0.5 on 2022-11-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221115_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='img',
            field=models.ImageField(null=True, upload_to='UserPhoto/%y'),
        ),
    ]
