# Generated by Django 3.0.5 on 2022-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221116_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='img',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
