# Generated by Django 3.0.5 on 2022-11-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
