# Generated by Django 3.0.5 on 2022-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='m_post',
            field=models.CharField(choices=[('LD', 'LAB_DIRECTOR'), ('RC', 'RESEARCH_COORDINATOR'), ('R', 'RESEARCHER'), ('LM', 'LAB_MEMBER')], default='LM', max_length=2),
        ),
    ]
