# Generated by Django 3.0.5 on 2022-11-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221120_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='google_scholor',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='members',
            name='orcid',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='members',
            name='research_gate',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
