# Generated by Django 3.0.5 on 2022-11-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20221121_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='fb',
        ),
    ]
