# Generated by Django 3.0.5 on 2022-11-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_members_fb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publisher_name", models.CharField(max_length=30)),
                ("research_title", models.TextField(max_length=1000)),
                ("paper_link", models.URLField(blank=True, max_length=300)),
            ],
        ),
    ]
