# Generated by Django 3.0.5 on 2022-11-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="research_title",
            field=models.CharField(max_length=100),
        ),
    ]
