# Generated by Django 3.0.5 on 2022-11-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20221122_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='journal',
            new_name='publication_type',
        ),
    ]
