# Generated by Django 3.0.5 on 2022-11-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
