# Generated by Django 3.0.5 on 2022-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(max_length=1000)),
                ('vision', models.TextField(max_length=1000)),
                ('we_do', models.TextField(max_length=1000)),
            ],
        ),
    ]
