# Generated by Django 3.0.5 on 2022-11-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_auto_20221123_1054"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Team",
        ),
    ]
