# Generated by Django 3.0.5 on 2022-11-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_testimonial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
    ]
