# Generated by Django 3.0.5 on 2022-11-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20221127_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='event/%y'),
        ),
    ]
