# Generated by Django 3.0.5 on 2022-11-29 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_conference_journal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Research_Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(null=True, upload_to="research/%y")),
            ],
        ),
        migrations.RenameModel(
            old_name="Year",
            new_name="Year_of_Publication",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.RemoveField(
            model_name="research",
            name="image",
        ),
        migrations.RemoveField(
            model_name="research",
            name="name",
        ),
        migrations.DeleteModel(
            name="Publication",
        ),
        migrations.AddField(
            model_name="research",
            name="category",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Research_Category",
            ),
        ),
    ]
