# Generated by Django 4.1.4 on 2024-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0038_auto_20221129_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="m_post",
            field=models.CharField(
                choices=[
                    ("LD", "LAB_DIRECTOR"),
                    ("LA", "LAB_ADVISOR"),
                    ("IC", "INTER_COLLABORATOR"),
                    ("RS", "RESEARCHER_STD"),
                    ("RA", "RESEARCHER_ALUMNI"),
                    ("RF", "RESEARCHER_FACULTY"),
                ],
                default="RS",
                max_length=2,
            ),
        ),
    ]
