# Generated by Django 5.1.3 on 2024-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_carousel_footer_alter_about_id_alter_achievement_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousel",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
