# Generated by Django 5.1.3 on 2024-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_carousel_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="member_carousel/")),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
