# Generated by Django 5.1.3 on 2024-12-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_membercarousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
