# Generated by Django 5.1.3 on 2024-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_team_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="team",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
